services:
  - type: web
    name: novacart
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: ADMIN_EMAIL
        value: admin@novacart.com
      - key: ADMIN_PASSWORD
        value: admin1234
